# Generated by Django 4.2.3 on 2023-08-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_price_listing_buyprice_listing_startprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='StatTrak',
            field=models.BooleanField(default=False),
        ),
    ]
